# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TagView_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'

  # Pods for TagView_Demo

  target 'TagView_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TagView_DemoUITests' do
    # Pods for testing
  end

end
