# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoa_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReactiveObjC'
  pod 'Masonry'

  # Pods for ReactiveCocoa_demo

  target 'ReactiveCocoa_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveCocoa_demoUITests' do
    # Pods for testing
  end

end
